apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: jotest-app
spec:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "a3fce062-845a-49a9-b9f2-3fa9e588032b"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET